#!/bin/sh
############################################################
#
#
############################################################
#
############################################################
L=64800
SUF=.one
IDX=YR
PRJ=GSW2
RUN=NEWN
#
YEARMIN=1986
YEARMAX=1995
YEARSIM=0000
############################################################
#
############################################################
CWSLNDMOS1STGRN0=../../crp/out/cwsg1st0/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDGRN0=../../crp/out/cwsg2nd0/${PRJ}${RUN}${SUF}
CWSLNDMOS1STRIV0=../../crp/out/cwsr1st0/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDRIV0=../../crp/out/cwsr2nd0/${PRJ}${RUN}${SUF}
CWSLNDMOS1STMSR0=../../crp/out/cwsm1st0/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDMSR0=../../crp/out/cwsm2nd0/${PRJ}${RUN}${SUF}
CWSLNDMOS1STNNB0=../../crp/out/cwsn1st0/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDNNB0=../../crp/out/cwsn2nd0/${PRJ}${RUN}${SUF}

CWSLNDMOS1STGRN1=../../crp/out/cwsg1st1/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDGRN1=../../crp/out/cwsg2nd1/${PRJ}${RUN}${SUF}
CWSLNDMOS1STRIV1=../../crp/out/cwsr1st1/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDRIV1=../../crp/out/cwsr2nd1/${PRJ}${RUN}${SUF}
CWSLNDMOS1STMSR1=../../crp/out/cwsm1st1/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDMSR1=../../crp/out/cwsm2nd1/${PRJ}${RUN}${SUF}
CWSLNDMOS1STNNB1=../../crp/out/cwsn1st1/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDNNB1=../../crp/out/cwsn2nd1/${PRJ}${RUN}${SUF}

CWSLNDMOS1STGRN2=../../crp/out/cwsg1st2/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDGRN2=../../crp/out/cwsg2nd2/${PRJ}${RUN}${SUF}
CWSLNDMOS1STRIV2=../../crp/out/cwsr1st2/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDRIV2=../../crp/out/cwsr2nd2/${PRJ}${RUN}${SUF}
CWSLNDMOS1STMSR2=../../crp/out/cwsm1st2/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDMSR2=../../crp/out/cwsm2nd2/${PRJ}${RUN}${SUF}
CWSLNDMOS1STNNB2=../../crp/out/cwsn1st2/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDNNB2=../../crp/out/cwsn2nd2/${PRJ}${RUN}${SUF}

CWSLNDMOS1STGRN3=../../crp/out/cwsg1st3/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDGRN3=../../crp/out/cwsg2nd3/${PRJ}${RUN}${SUF}
CWSLNDMOS1STRIV3=../../crp/out/cwsr1st3/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDRIV3=../../crp/out/cwsr2nd3/${PRJ}${RUN}${SUF}
CWSLNDMOS1STMSR3=../../crp/out/cwsm1st3/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDMSR3=../../crp/out/cwsm2nd3/${PRJ}${RUN}${SUF}
CWSLNDMOS1STNNB3=../../crp/out/cwsn1st3/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDNNB3=../../crp/out/cwsn2nd3/${PRJ}${RUN}${SUF}

CWSLNDMOS1STGRN4=../../crp/out/cwsg1st4/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDGRN4=../../crp/out/cwsg2nd4/${PRJ}${RUN}${SUF}
CWSLNDMOS1STRIV4=../../crp/out/cwsr1st4/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDRIV4=../../crp/out/cwsr2nd4/${PRJ}${RUN}${SUF}
CWSLNDMOS1STMSR4=../../crp/out/cwsm1st4/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDMSR4=../../crp/out/cwsm2nd4/${PRJ}${RUN}${SUF}
CWSLNDMOS1STNNB4=../../crp/out/cwsn1st4/${PRJ}${RUN}${SUF}
CWSLNDMOS2NDNNB4=../../crp/out/cwsn2nd4/${PRJ}${RUN}${SUF}
############################################################
#
############################################################
htmean $L $CWSLNDMOS1STGRN0$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDGRN0$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS1STRIV0$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDRIV0$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS1STMSR0$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDMSR0$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS1STNNB0$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDNNB0$IDX $YEARMIN $YEARMAX $YEARSIM

htmean $L $CWSLNDMOS1STGRN1$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDGRN1$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS1STRIV1$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDRIV1$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS1STMSR1$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDMSR1$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS1STNNB1$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDNNB1$IDX $YEARMIN $YEARMAX $YEARSIM

htmean $L $CWSLNDMOS1STGRN2$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDGRN2$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS1STRIV2$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDRIV2$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS1STMSR2$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDMSR2$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS1STNNB2$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDNNB2$IDX $YEARMIN $YEARMAX $YEARSIM

htmean $L $CWSLNDMOS1STGRN3$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDGRN3$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS1STRIV3$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDRIV3$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS1STMSR3$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDMSR3$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS1STNNB3$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDNNB3$IDX $YEARMIN $YEARMAX $YEARSIM

htmean $L $CWSLNDMOS1STGRN4$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDGRN4$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS1STRIV4$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDRIV4$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS1STMSR4$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDMSR4$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS1STNNB4$IDX $YEARMIN $YEARMAX $YEARSIM
htmean $L $CWSLNDMOS2NDNNB4$IDX $YEARMIN $YEARMAX $YEARSIM

